import type { JournalEntry, CreateJournalEntryInput } from '@/types/journal';

export const mockJournalEntry: JournalEntry = {
  _id: 'journal-1',
  userId: 'user-1',
  symbol: 'BTCUSDT',
  interval: '1h',
  signalScore: 45,
  signalTier: 'buy',
  action: 'buy',
  entryPrice: 42000,
  exitPrice: null,
  outcomePnlPercent: null,
  notes: 'Strong momentum signal',
  reviewedAt: null,
  tags: ['breakout', 'trend-follow'],
  indicatorSnapshot: {
    rsi: 62,
    macdLine: 150,
    macdSignal: 120,
    macdHistogram: 30,
    bollingerUpper: 43000,
    bollingerMiddle: 42000,
    bollingerLower: 41000,
    ema12: 42100,
    ema26: 41900,
    sma50: 41500,
    sma200: 40000,
    atr: 500,
    stochRsiK: 75,
    stochRsiD: 70,
    williamsR: -25,
    obv: 1500000,
    mfi: 60,
    superTrendDirection: 'up',
    fearGreedIndex: 65,
    fearGreedLabel: 'Greed',
  },
  strategyId: null,
  backtestResultId: null,
  lessonsLearned: '',
  reviewHistory: [],
  setupType: 'breakout',
  marketCondition: 'trending_up',
  sentiment: { fearGreedIndex: 65, fearGreedLabel: 'Greed' },
  createdAt: '2025-01-01T00:00:00.000Z',
  updatedAt: '2025-01-01T00:00:00.000Z',
};

export const mockJournalEntry2: JournalEntry = {
  _id: 'journal-2',
  userId: 'user-1',
  symbol: 'ETHUSDT',
  interval: '4h',
  signalScore: -35,
  signalTier: 'sell',
  action: 'sell',
  entryPrice: 2200,
  exitPrice: 2100,
  outcomePnlPercent: 4.55,
  notes: 'Bearish crossover confirmed',
  reviewedAt: new Date('2025-01-02T12:00:00.000Z') as unknown as null,
  tags: ['reversal'],
  indicatorSnapshot: null,
  strategyId: 'strategy-1',
  backtestResultId: null,
  lessonsLearned: 'Good entry timing, should have held longer',
  reviewHistory: [],
  setupType: 'reversal',
  marketCondition: 'trending_down',
  sentiment: { fearGreedIndex: 25, fearGreedLabel: 'Fear' },
  createdAt: '2025-01-02T00:00:00.000Z',
  updatedAt: '2025-01-02T12:00:00.000Z',
};

export const mockSkippedEntry: JournalEntry = {
  _id: 'journal-3',
  userId: 'user-1',
  symbol: 'SOLUSDT',
  interval: '15m',
  signalScore: 5,
  signalTier: 'neutral',
  action: 'skip',
  entryPrice: null,
  exitPrice: null,
  outcomePnlPercent: null,
  notes: 'Too weak to act on',
  reviewedAt: null,
  tags: [],
  indicatorSnapshot: null,
  strategyId: null,
  backtestResultId: null,
  lessonsLearned: '',
  reviewHistory: [],
  setupType: '',
  marketCondition: null,
  sentiment: null,
  createdAt: '2025-01-03T00:00:00.000Z',
  updatedAt: '2025-01-03T00:00:00.000Z',
};

export const mockJournalEntries: JournalEntry[] = [
  mockJournalEntry,
  mockJournalEntry2,
  mockSkippedEntry,
];

export const mockCreateJournalInput: CreateJournalEntryInput = {
  symbol: 'BTCUSDT',
  interval: '1h',
  signalScore: 45,
  signalTier: 'buy',
  action: 'buy',
  entryPrice: 42000,
  notes: 'Strong momentum signal',
  tags: ['breakout'],
  setupType: 'breakout',
  marketCondition: 'trending_up',
};
